# Generated by Django 6.0.3 on 2026-03-18 14:54

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Deployment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('DEPLOYING', 'DEPLOYING'), ('RUNNING', 'RUNNING'), ('FAILED', 'FAILED'), ('STOPPED', 'STOPPED')], default='DEPLOYING', max_length=20)),
                ('endpoint_url', models.TextField(blank=True, null=True)),
                ('runtime_type', models.CharField(default='in_memory', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
