# Generated by Django 6.0.3 on 2026-03-18 14:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('deployments', '0001_initial'),
        ('model_registry', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deployment',
            name='model_version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deployments', to='model_registry.modelversion'),
        ),
    ]
