# Generated by Django 6.0.3 on 2026-03-18 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UsageMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('request_count', models.IntegerField(default=0)),
                ('error_count', models.IntegerField(default=0)),
                ('avg_latency', models.FloatField(default=0)),
            ],
        ),
    ]
